### ISSUE TITLE
[BUG]: Client timing out after refresh

### ISSUE THREAD

**Issue by MinecraftMoments** [TheHunterManX/GBA-PK-multiplayer#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

![image](https://user-images.githubusercontent.com/84159674/202673373-8d58eec2-fda0-4c1c-864b-d2b00938e906.png)
Closed out mGBA to try and change my nickname on the server, now it will not let friend join and keeps timing them out. Reverting to the non-nicknamed one seems to have fixed the issue even though i would like to customize my name on the connected game

### Steps To Reproduce

Play game
Work fine
Save and exit 
Edit .lua file to have new nickname (5 character long)
Game now not connecting properly

**Comment by Zadowcloud** [comment]
I encountered that issue too
Maybe you need to change on both but i haven't tried it yet

**Comment by televisionia** [comment]
Try using a nickname that is 4 characters or less on the server, there's a major bug I've found that I have explained here #41

**Comment by TheHunterManX** [comment]
This will be fixed in the Alpha 3.5 update coming out within 2 weeks
