### ISSUE TITLE
can't connect over the internet (port forwarding)

### ISSUE THREAD

**Issue by epaluy** [TheHunterManX/GBA-PK-multiplayer#10]
I found my private ip in settings where it says "IPv4 Adress:"
and the public ip, i just googled whats my ip

I can't connect a device over the internet
I port forwarded with my IPv4 address (private) and both protocols for port 4096
i tried to join the server when the client having the private ip and the public one. both of them didn't work
the public ip didn't work when trying to connect to in the same pc but the private one did
i don't know what to do.

if anyone can make a video for this it would be really helpful
or you can explain please

ps:
i watched the instruction video and i still don't know how i can connect internationally

2nd ps:
i got it working after following the tutorial here
https://www.youtube.com/watch?v=X8ry7c7HJIo
The part of the "Allow trough firewall"

3rd ps:
if anyone is interested, i can make a video tutorial on installing and connection

**Comment by SWHSmash** [comment]
same issue. better keep it on one thread. :)

#7

**Comment by Faloigi** [comment]
ye i really need your video cause i maked all the steps in the video and allowed trough firewall too with the port 4096 but when i start the host and my friend start the client my friend doesnt connect to the server.
(There are a screen of pov by my friend)
![image](https://user-images.githubusercontent.com/65950084/205509365-19908fcd-89f2-4252-84ad-9ca0e8af5cb2.png)
