### ISSUE TITLE
[Question]: Can you change the nickname?

### ISSUE THREAD

**Issue by ZoranaDragon** [TheHunterManX/GBA-PK-multiplayer#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Is there a way to change the nickname so it's not a jumble of random lowercase letters? It's not necessarily important but it'd be nice to have it use the names on the save files if possible. 

### Steps To Reproduce

This box is required to fill out and I'm not sure how to do something other than a bug report to ask this. Sorry, this is my first time using Github for this.

**Comment by ultimate-vegan** [comment]
yes you have to go into the lua file and change the value of "local Nickname" to what you want your nickname to be. beware though that other users (#1) are experiencing connection problems when using custom nicknames. my friend and I weren't able to use nicknames or else we would get that time out bug.

**Comment by mastercuber55** [comment]
Go to Server.lua And Copy Code Of Line From 21633 To 21635.
Go To Client.lua Line 21529 And Paste Code You Copied Earlier.
Go To Line 3 And Put Whatever You Want Like You Can In Server.lua(Please Note The 4 Letter Limit)
I'm Trying To Push Beyond 4 Letters But It Didn't Worked Out Yet, I'll Reply Again If I Push Beyond.

**Comment by televisionia** [comment]
The clients for some reason cannot have custom nicknames, it always gets randomized regardless..

**Comment by mastercuber55** [comment]
@televisionia , I literally told how to do that in my previous comment and also mentioned 4 Letter Requirement.

**Comment by televisionia** [comment]
@mastercuber55 wait, copying and pasting the server functions to the client script fixes the issue? You should find out how that works and make a PR fixing the issue.

**Comment by televisionia** [comment]
@mastercuber55 PR stands for pull request, sorry for the confusion.

**Comment by mastercuber55** [comment]
@televisionia Sorry but idk how to do that, its simple so you may do it yourself though.

**Comment by TheHunterManX** [comment]
as long as it is 4 letters in Alpha 3.0 then it will work.
