### ISSUE TITLE
[SUGGESTION]: Add Discussions to the repository.

### ISSUE THREAD

**Issue by televisionia** [TheHunterManX/GBA-PK-multiplayer#14]
I would love a way for us to communicate a bit better and be able to ask questions about the script's progress. Plus some talk about the technical side. I've noticed a lot of people throwing "bug reports" complaining that they can't figure out how the script works and cant use features that aren't even finished yet. I would like to ask questions alpha V3 as well, but unfortunately the repositories doesn't have discussions enabled. It would also be a nice thing to have before we get a pokecommunity forum. If there is already something like this that exists, please let me know.

**Comment by CrushedBard971** [comment]
I agree the only place to discuss and help people is the comments on YouTube or GitHub. A discord server could also be helpful.

**Comment by televisionia** [comment]
> A d

Yeah, a discord server would be awesome

**Comment by TheHunterManX** [comment]
Thank you for the tip.
