### ISSUE TITLE
[BUG]: Pokemon Emerald Detected, script disabled

### ISSUE THREAD

**Issue by TigoBurrito** [TheHunterManX/GBA-PK-multiplayer#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

when i tried to put the server file or client file in the scripting area they just didnt work.

### Steps To Reproduce

I did everything that the video said to do

**Comment by SWHSmash** [comment]
This script only works for FR/LG currently and won't work with emerald for now. That was the first game I tested out before I take a look into the code and found currently only support for FR/LG.

**Comment by televisionia** [comment]
The above reply is correct, this will only work with Firered and Leafgreen. I don't know when TheHunterManX will add support, but keep an eye out.

**Comment by TheHunterManX** [comment]
This will be added in Alpha 3.5, which is coming within 2 weeks.
