### ISSUE TITLE
I can't figure how to make this work with Hamachi. I just can't connect to my friend.

### ISSUE THREAD

**Issue by iGrOdAcz** [TheHunterManX/GBA-PK-multiplayer#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I can't figure how to make this work with Hamachi. I just can't connect to my friend.

We did everything and we can't just get it to work. If anyone knows how to do it please tell me. There is huge possibility that we are just dumb.

### Steps To Reproduce

.

**Comment by televisionia** [comment]
Try using ZeroTier instead (look up tutorials on how to use it, the way you would use it for Minecraft servers is kind of the same for this script.)
If you still want to try to get Hamachi to work, first of all make sure you're both on Windows, they don't really support the mac version anymore. Make sure you and your friend are both connected to the network in Hamachi and that the network is on, then copy the IPv4 address next to the power button. Set the IP address in the server script to that IP address, leave the port as the same as it was before. Get your friend to do the same but with the client script. (If you don't know what the difference between server and client is just look it up)

Now you should be able to connect, hopefully. I might have missed a important detail, update me on how it goes. Make sure the server script runs FIRST, then your friend runs the client script. MGBA might freeze for a bit, however it doesn't mean it's not working, just be patient.

**Comment by Faloigi** [comment]
> Try using ZeroTier instead (look up tutorials on how to use it, the way you would use it for Minecraft servers is kind of the same for this script.) If you still want to try to get Hamachi to work, first of all make sure you're both on Windows, they don't really support the mac version anymore. Make sure you and your friend are both connected to the network in Hamachi and that the network is on, then copy the IPv4 address next to the power button. Set the IP address in the server script to that IP address, leave the port as the same as it was before. Get your friend to do the same but with the client script. (If you don't know what the difference between server and client is just look it up)
> 
> Now you should be able to connect, hopefully. I might have missed a important detail, update me on how it goes. Make sure the server script runs FIRST, then your friend runs the client script. MGBA might freeze for a bit, however it doesn't mean it's not working, just be patient.

This comment saved me and my friend for all people who cannot make port forwarding do this.

**Comment by televisionia** [comment]
@Faloigi Glad it's working for you!
