### ISSUE TITLE
battling doesnt work[BUG]: 

### ISSUE THREAD

**Issue by KeemSenpai** [TheHunterManX/GBA-PK-multiplayer#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

battling doesnt work only trading

### Steps To Reproduce

tried to battle

**Comment by SWHSmash** [comment]
battles aren't implemented yet

**Comment by TheHunterManX** [comment]
Battling will be added in Alpha 4.0
