### ISSUE TITLE
[BUG]: PVP doesnt work

### ISSUE THREAD

**Issue by CDonalO** [TheHunterManX/GBA-PK-multiplayer#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Cant initiate battle with other player

### Steps To Reproduce

Try to battle

**Comment by Zadowcloud** [comment]
Battles will be released with Alpha 3

**Comment by CrushedBard971** [comment]
PVP isn't coming until a later update.

**Comment by SWHSmash** [comment]
> Battles will be released with Alpha 3

alpha 3 is here and still no support for battling, just 4 players. :D

**Comment by Zadowcloud** [comment]
He delayed it. It will be out with Alpha 4.0 hopefully =)

**Comment by TheHunterManX** [comment]
This will be added in Alpha 4.0, which is not out yet
