### ISSUE TITLE
[BUG]: Doesn't work at all. 

### ISSUE THREAD

**Issue by DevilishWeb3692** [TheHunterManX/GBA-PK-multiplayer#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Not able to connect to each other even though we did everything right. 

### Steps To Reproduce

My friend and I have watched a tutorial and did everything the exact same way as the people in the video did and it doesn't work. I downloaded the Server and Client lua files, I changed the IP to the Hamachi iPv4 for both, then sent my friend the client file. We both opened Fire Red, I started my script, he started his after, and it didn't connect, only leaving him with a "Connected to server: No" message. We tried Alpha 3, then tried Alpha 2.6.1 and it gave me the "Player 2 Disconnected" message, but still wouldn't let my friend connect. The IP is correct and we didn't touch anything else in the lua file. We also tried connecting to my personal IP address and it still didn't work.

**Comment by televisionia** [comment]
Check out the advice I gave in #17 , If nothing works, try out ZeroTier. Find a tutorial on how to use it (like one for setting up a minecraft server, but just follow the parts where you make the network and get the ip address and do the rest for the script on your own. You only need to change the IP address) Make sure you and your friend are connected to the same network in Hamachi, same with ZeroTier. Also know that sometimes the client takes a bit to connect, and can cause mgba to freeze for a bit (not meaning its crashed, but if it does freeze for way too long (like more than 5 minutes) then it probably cant find the connection.)

**Comment by DevilishWeb3692** [comment]
> same issue in #5 use this thread for research or answers pls instead creating the same issue over and over again!
> 
> pls close!

It’s not the same issue though? #5 states that they don’t know how to get it to work despite watching the tutorial. Mine should be working since we’ve done everything correctly, and yet it’s not

**Comment by televisionia** [comment]
@DevilishWeb3692 Have you tried using ZeroTier yet? Another user had their problem solved after using ZeroTier.

**Comment by televisionia** [comment]
This might be caused from a major bug where clients cant connect when the server has its nickname longer than 4 characters. I have a more in-depth explanation about the problem here #41
