### ISSUE TITLE
[BUG]: Cant see my friend

### ISSUE THREAD

**Issue by Faloigi** [TheHunterManX/GBA-PK-multiplayer#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Me and my friend are connected but when start game we cant see eachothers in the game, i dont know why i think nobody has this problem.
If someone know how to fix that pls tell me.
(The problem can be caused by my friend connection i think cause if i look in the script screen i can see him to disconnect and riconnect sometimes.
![immagine_2022-12-06_190809461](https://user-images.githubusercontent.com/65950084/205988455-3cfbb57a-08e0-4b69-b313-ae633c67bfbe.png)
)

### Steps To Reproduce

.

**Comment by televisionia** [comment]
This usually happens from lag, I've only had this issue rarely and not for long. This could be from them having the emulator minimized and it pausing or just simply a bad connection. Especially if you are both overseas from each other. It could be to do with the update, however, but if you haven't switched to alpha 3, please do as it has better performance changes. Your save files should still be perfectly fine as they are based on the actual game, the script just makes you see each other and trade.

**Comment by Faloigi** [comment]
me and my friend has controlled the connection and it is ok, so the problem isnt the lag.
Idk why we're connected but in the game we cant see eachothers.

**Comment by televisionia** [comment]
That's strange, are you both using the same ROM version? both 1.1 or both 1.0?

**Comment by Faloigi** [comment]
were using the 1.1 version of the ROM, and it still dont work so tell me if i need to use the 1.0.
I've see a probably bug, in the client script when i start it say **Connected to server: No** but in the server script i can see the connection.

![image](https://user-images.githubusercontent.com/65950084/206451585-899420b0-e682-47eb-892e-5f669e7ce598.png)
but i repeat in the server script are write the connection so were connected but the client script say this.

**Comment by televisionia** [comment]
Oh, are you both using Alpha V3? If you are really still using alpha 3, then it must be a problem with the actual script. Maybe try redownloading alpha v3's scripts and edit the ip address again. Make sure you and your friend have the same scripts (you edit the client for him and send it to him and then you set up the server and run it)

**Comment by Faloigi** [comment]
it finally works thanks!!!

**Comment by televisionia** [comment]
No problem!
