### ISSUE TITLE
I dont know how to trade

### ISSUE THREAD

**Issue by GuiTheDev** [TheHunterManX/GBA-PK-multiplayer#23]
So I have been playing with my friend, but we cant trade, I have tried to do it in a PokeCenter, but it just says "Please wait" for both of us, is this a bug or am I not doing it right?

**Comment by televisionia** [comment]
Shown on the creator's youtube showcase videos, it does not work like that. This isn't a cable link connection. Conveniently, it's actually much more easier to trade than having to walk to a pokecenter. You just have to interact with the other player's character (by pressing A on them, or whatever keybind is set to your gba's A button in your emulator) and you will be given the option to.

**Remember that you can only trade wth players at the moment, player versus player battling will be added in Alpha 4.**
