### ISSUE TITLE
[BUG]: Help With Port

### ISSUE THREAD

**Issue by TysonKnot** [TheHunterManX/GBA-PK-multiplayer#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Me and my buddy cannot get this to work at all, I have followed the video and everything, this is different to others as I would like to clarify does the port 4096 remain the same and only the IP gets change?

### Steps To Reproduce

Download files

follow video

**Comment by SWHSmash** [comment]
hi
check twice the scripts ips. the host/server must use the internal local IP (starts normally with 192.168.X.X) and the client must use the external ip (check it via google and whatismyip - and keep in mind that these change daily!)
also the host must forward the port to the internal ip!

else use the advice from [@televisionia](https://github.com/televisionia) at issue [#17](https://github.com/TheHunterManX/GBA-PK-multiplayer/issues/17#issuecomment-1337159861) :)

~SWHSmash
