### ISSUE TITLE
Hope to add different language versions

### ISSUE THREAD

**Issue by ashgx** [TheHunterManX/GBA-PK-multiplayer#28]
I tested the Pokemon firered Japanese version and the Pokemon leafgreen Japanese version, and the results are as follows:
![5014](https://user-images.githubusercontent.com/81661156/207745124-9bd967fd-9c95-44c4-b3b2-b075a62d51e0.jpg)

**Comment by SWHSmash** [comment]
#rtdm
currently only FR/LG v1.0 and v1.1 US roms are supported.

**Comment by televisionia** [comment]
I think having more language support is a good suggestion.

**Comment by TheHunterManX** [comment]
I agree it is a good feature ;)
