### ISSUE TITLE
Issue figuring out how to have friend connect to my server

### ISSUE THREAD

**Issue by GingerFlash** [TheHunterManX/GBA-PK-multiplayer#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I open a server while my friend opens a client, and being unexperienced with stuff like this we aren't exactly sure how to connect to each other and would just like to know how to do that, Thanks!

### Steps To Reproduce

I open server side

Friend opens client side

Where do we go from there

**Comment by Zadowcloud** [comment]
https://www.youtube.com/watch?v=Nu4Yb7vOx0k&ab_channel=TheHunterManX
Try this :)

**Comment by fancythedeveloper** [comment]
This isn't a bug

**Comment by ArtMatters** [comment]
1. Watch a video guide for port forwarding Minecraft.
2. Whoever does the port forwarding has to have the server file.
3. Whoever connects has to have the client file.
4. Change the port from the video to the one for Pokemon.
5. Change the IP in the client file to the visible IP of the host.
6. Make sure the host has a static IP.
