### ISSUE TITLE
[BUG]: Friend can't join (we use Hamachi)

### ISSUE THREAD

**Issue by Eggbot-The-Great** [TheHunterManX/GBA-PK-multiplayer#30]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the bug

We use **Hamachi** and whenever we put in the same ip and then run the script, his crashes and we tried to add **":4096"** right after the ip in the speech marks in the code and then he doesn't crash but instead the client script cannot find a connection.

is there something wrong in the code or inside Hamachi?
a response would be greatly appreciated. Many thanks  >=]  

### Steps To Reproduce

. Download scrips
. Use Hamachi ip in both client and server ip area
. Open server first
. Friend opens client script and it crashes
. Friend cannot connect

**Comment by SWHSmash** [comment]
Try using ZeroTier instead (look up tutorials on how to use it, the way you would use it for Minecraft servers is kind of the same for this script.)
If you still want to try to get Hamachi to work, first of all make sure you're both on Windows, they don't really support the mac version anymore. Make sure you and your friend are both connected to the network in Hamachi and that the network is on, then copy the IPv4 address next to the power button. Set the IP address in the server script to that IP address, leave the port as the same as it was before. Get your friend to do the same but with the client script. (If you don't know what the difference between server and client is just look it up)

Now you should be able to connect, hopefully. I might have missed a important detail, update me on how it goes. Make sure the server script runs FIRST, then your friend runs the client script. MGBA might freeze for a bit, however it doesn't mean it's not working, just be patient.

_Originally posted by @televisionia in https://github.com/TheHunterManX/GBA-PK-multiplayer/issues/17#issuecomment-1337159861_

**Comment by Eggbot-The-Great** [comment]
ive done all those steps all correctly and still nothing is working

**Comment by televisionia** [comment]
@Eggbot-The-Great Have you tried using ZeroTier yet?

**Comment by TrueBloo** [comment]
i tried zerotier still nothing i alkso tried hamachi and Radmin Vpn it just isn't connecting for some reason
