### ISSUE TITLE
[BUG]: Having bad stutters when attempting to run client script.

### ISSUE THREAD

**Issue by IDaPanda5000** [TheHunterManX/GBA-PK-multiplayer#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

A friend and I tried to set everything up today once I found this existed.  It works perfectly for me, but for my friend once he starts to run the lua script the emulator plays for a second then it's like it pauses for another few seconds then plays a second and repeats this cycle, and nothing gets done.  

He can run mGBA just fine without attempting to run the script and it works perfectly fine, but as soon as he attempts to run the script it stutters as stated above.  We both have the same exact emulator versions, script versions, and game versions.

He has tried to update his drivers and that does not change anything.  Any help or thoughts on the issue would be helpful.  Unsure if this a problem on his end or the scripts end.

### Steps To Reproduce

Start mGBA.

Run Pokemon Fire Red, though not past the main menu with Charizard on it.

Attempt to start the Client lua script

Emulator starts stuttering extremely bad (Though only for my friend, and it works perfectly for me)

**Comment by televisionia** [comment]
Could you explain the process you have gone through to get the connection working? Did you port forward or use a virtual network?

**Comment by IDaPanda5000** [comment]
I have used Hamachi, though it happens even when I don't have the server up
and running.

**Comment by televisionia** [comment]
Keep in mind that, from self experience and many others experience, sometimes the client takes a bit to connect and the emulation freezes. This is normal, It's only not normal when it doesn't finish connecting for a very long time, showing that it is having trouble finding a connection to the host. If the case is that it isn't working even waiting after ages, maybe use ZeroTier as a alternative. It's free and open source and runs on all devices, though you'd have to look up some tutorials on how to use it (pretty much the same as minecraft server tutorials, just focus on the creating the network part. There's those kinds of tutorials out there for ZeroTier.)

And on another note, you have to do it while your friend is connected to your Hamachi network. You can look up on youtube how to join other people's hamachi network. Make sure the IP address in BOTH the server and client script is equal to IPv4 address shown next to the power off icon on the hamachi app. You shouldn't need to change the port from self experience, but I mainly use ZeroTier so Hamachi might be different.
(Here's a good video for convenience, this will work with most LAN games, just skip the minecraft part, get your friend to do the firewall changes in the video too if it still doesnt work: https://www.youtube.com/watch?v=kOJcQVNn1t4)

Please let me know if there's any more problems.
