### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by saltycanuk** [TheHunterManX/GBA-PK-multiplayer#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

so ive port frowarded properly according to the internet (mind you it was 2 different sites and it was the same steps) and i followed the tutorial video on the page and i cannot connect with a friend they cannot connect to my server script, it doesnt even register them looking for my server file.... ive not tried 3rd party programs as i was told by the tutorial that port forwarding was good enough so if i need a 3rd party program let me know i guess

### Steps To Reproduce

i download game after port forwarding and run scripts for server and my friend runs scripts for client with the port forwarded port and ip and it doesnt do anything

**Comment by Necrosis000** [comment]
Did you change the 
![image](https://user-images.githubusercontent.com/57779109/209884866-abadba11-c560-4341-8d9a-2560000b2c55.png)
IP to the one you use?

**Comment by Necrosis000** [comment]
This is in the server lua file btw

**Comment by saltycanuk** [comment]
yes i have
on both server and client file

**Comment by televisionia** [comment]
You might have to use ZeroTier or Hamachi instead, its a bit like doing a minecraft LAN game with your friend over a virtual network, but with this lua script.

**Comment by Necrosis000** [comment]
Another question is the ip in the server file 127.0.0.1 and the client ip the one you have? That was what I did wrong the first time

**Comment by televisionia** [comment]
Might be caused from a major bug where the server is broken if the server's nickname is set to longer than 4 characters (in-depth explanation here: #41 )
