### ISSUE TITLE
[BUG]: Battling doesnt work.

### ISSUE THREAD

**Issue by Trizzle1775** [TheHunterManX/GBA-PK-multiplayer#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When me and my friend try to battle each other it says that nothing happened? can this be fixed?

### Steps To Reproduce

.

**Comment by televisionia** [comment]
Just a quick note before I explain: Please check other issues to see if your problem has already been answered. (your issue is a duplicate of #19 and #2)

Battles have not been implemented yet, they will be added in the Alpha 4 update.

**Comment by TheHunterManX** [comment]
Yep Alpha 4
