### ISSUE TITLE
[BUG]: A question regarding compatibility

### ISSUE THREAD

**Issue by AlixTheRed** [TheHunterManX/GBA-PK-multiplayer#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Less a bug and more a question of compatibility, is this usable with other versions of firered? I found this through smallant's video and in it he is playing with someone else using a fire red that has randomized pokemon for all as well as a 'kill' feature to faint pokemon. I managed to get this to connect using a base firered, but when attempting to have the client connect to a fire red that was more modified(a randomizer and gens 1-8) the client would just freeze and stutter every second without making an attempt to connect. I changed nothing with either lua between the ROMs, so why did one work but not the other? Even in the gba scripts window did the script recognize the game as fire red and didnt show any errors.

I am just a lil confused on the exact extent of modfying one can do to the fire red rom before it becomes unable to load right. Anyhelp would be greatly appreciated. 

### Steps To Reproduce

- Run gba
- launch modified fire red rom
- start server lua
- start client lua

**Comment by televisionia** [comment]
This is actually a interesting question, I'm not very experienced in actual ROM hacking so I cant be too sure. However I do know that the game name would probably be in the ROM data, so no matter what you name the FireRed file, it will still detect it as firered. So I'd assume that the script works as long as something isnt changed that the script depends on. Like game locations, trading system and stuff. If it adds more pokemon into the game it would probably confuse the script and cause it to halt.

**Comment by AlixTheRed** [comment]
Ah, so, funnily enough it was actually more user error on my part with the non-connecting... Turns out I didnt realize that having a local nickname set would cause the time out issues, but after reading that in one of these posts and removing them, we were able to connect instantly and just fine. 

Now there are a few more quirks going on(showing same player model even though a different one was selected, seeing other player through up/down floors etc.) but I am unsure if those are a result of the extra stuff in the rom or just the script. Either way, it doesnt affect that much.

**Comment by televisionia** [comment]
Alright, yeah, the script is probably made for unmodified ROMs so, cant guarantee it to be a 100% smooth experience. Plus, it's in alpha phase too. Glad that you are connected now, the nickname problem could be to do with problems with sending data over to the server.

**Comment by TheHunterManX** [comment]
So when Alpha 3.5 comes out it will have a list of addresses in the file. To make a detailed explanation short, if those addresses are modified it can break the script. I suggest using rom hacks that are small in nature.
