### ISSUE TITLE
[BUG]: stuck in npc dialouge

### ISSUE THREAD

**Issue by sus12312** [TheHunterManX/GBA-PK-multiplayer#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Okay so thank you so much for enabling me to play multiplayer firered but, I have run into a problem of being stuck in NPC dialogue. I really don't want to restart and I would like help. When I hit any button nothing happens. B, A, Start, Select, nothing. 
<img width="1057" alt="Screenshot 2023-02-19 at 8 40 31 AM" src="https://user-images.githubusercontent.com/92955150/219951944-f709179c-5cdf-4e8b-9b96-30eb4f727677.png">

### Steps To Reproduce

Open MGBA
Load up legal rom
Load save state
Stuck in NPC dialouge, the girl on top of celadon shopping center.

**Comment by televisionia** [comment]
Have you been saving your game states? I HIGHLY recommend doing so. It appears this is a bug in the script maybe to do with how the script interacts with the inventory system? I'm not sure. We'll have to wait and see if @TheHunterManX fixes this one.

**Comment by TheHunterManX** [comment]
After a bit of testing in Alpha 3.5, this doesn't seem to be an issue anymore.
