### ISSUE TITLE
[BUG]: Client Shows as Connected then Repeatedly Timed out on Server 

### ISSUE THREAD

**Issue by Oraceon** [TheHunterManX/GBA-PK-multiplayer#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I have tried both Port-forwarding and Hamachi. I have a lot of experience port-forwarding, so I know that is not the issue. When the client connects to my server using my public IP, it shows on my script menu that the client has connection, but then has timed out. It will do this numerous times and the connection will never actually be stable. On the client side, it shows that no connection has taken place whatsoever. It gives them a random username even after entering the Client's own. And on top of that, it says "Connected to server: no" even though on the Server side it shows that the connection was attempted and then timed out. 

At no point are we able to see or communicate with each other in game. We are playing across the country, so this is not a LAN issue. Furthermore, its not a firewall issue as I host Minecraft and DayZ servers with minimal connection problems. We have checked both script files repeatedly for misspellings or wrong information, and that is not the case. I have found zero information online about this - only people complaining about the issue in YouTube comments, but no answers or responses.

This issue is repeatably and makes it impossible for us to play at all.

### Steps To Reproduce

1) Run mGBA and launch your ROM
2) Run the script
3) Nothing works

**Comment by televisionia** [comment]
Oh one thing I forgot to mention about the nicknames, nicknames are pretty broken. Try leaving the nickname blank in the script for all clients ("") when hosting (try this with port forwarding). I think this may be due to the amount of data sent through being limited, causing the script to halt. though I can't be too sure..

**Comment by Oraceon** [comment]
Thanks for the quick response. I'll give it another shot later, but this time with both nicknames blank. I'll update you as soon as its done.

**Comment by Oraceon** [comment]
I can now confirm that leaving the nickname fields blank in both Server and Client did fix the timing out and Client connection issue. Been working for over an hour now with little issues except for some minor desync. Thanks for your help, @televisionia

**Comment by televisionia** [comment]
Awesome! @Oraceon I might go post an issue (might even do a pull request to fix the issue too!) regarding the nickname bug/glitch problem.

**Comment by televisionia** [comment]
Just made one at #41 , it seems you were definitely not alone
