### ISSUE TITLE
[BUG]: Cancelling a Trade will Cause the Client to Freeze

### ISSUE THREAD

**Issue by Oraceon** [TheHunterManX/GBA-PK-multiplayer#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When opening a trade via direct communication with a player in game, the game will state "Waiting for other player" and then a trade menu will open only on the Host's game. Furthermore, in the trade, you are only able to choose party Pokemon and not box Pokemon. I do not know if this is intended. However, after seeing that I could only choose party Pokemon, I cancelled the trade, and my trading partner (the client) was still stuck on the dialogue box "waiting for other player" while I was able to move around freely with no issues. The client is unable to perform any actions whatsoever and is permanently stuck. Unfortunately there is no way around this as making a save state at this point will throw you back into the dialogue freeze, so its best to manually save your game before initiating a trade.

### Steps To Reproduce

1) Initiate a trade via the p2p dialogue menu
2) Cancel the trade when option is available

**Comment by televisionia** [comment]
Looks like another thing @TheHunterManX is gonna have to look into.

**Comment by Oraceon** [comment]
He certainly has a lot on his plate, but building a multiplayer framework into an exclusively-singleplayer game mode is very difficult, and I commend him for it. There is expected to be several bugs. Hopefully with enough reports, we can get them resolved, and this mod will be a lot easier to use.

**Comment by TheHunterManX** [comment]
Trading is much more reliable in Alpha 3.5, so it will be fixed.
