### ISSUE TITLE
[BUG]: When a Player is on the Same Coordinate Tile in a Different Location, You Can Still Interact with the Tile as if The Player is There

### ISSUE THREAD

**Issue by Oraceon** [TheHunterManX/GBA-PK-multiplayer#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

My friend (client) is inside the Pokemon Center in Pewter City. They are currently standing in front of the Pokemon Center Counter actively engaged in dialogue with the nurse. I am outside of Mt. Moon on the Pokemon Center right of the rocks. I randomly decided to test the matching coordinates of both locations, and I am able to interact with the rock pictured below as if it was my friend.

Doesn't seem to actually cause any issues outside of a small inconvenience say for example if a hidden item happens to be in a location coordinate relative to where your friends are.

![image](https://user-images.githubusercontent.com/125865513/220431782-0da7889c-3fe6-46a1-8ac7-f2c0a6fb520d.png)

### Steps To Reproduce

1) Find your friends' coordinate
2) Locate that coordinate on a different map
3) Interact with the coordinate

**Comment by televisionia** [comment]
Woah, this is pretty goofy. It's probably because of how the script probably isn't able to tell what location the player is in, or at least all the clients are in. Let's see if this one is fixed in the future.

**Comment by TheHunterManX** [comment]
Funny enough, that was something still in 3.5. Now it is fixed.
