### ISSUE TITLE
[BUG]: Trading doesn't work at all

### ISSUE THREAD

**Issue by Oraceon** [TheHunterManX/GBA-PK-multiplayer#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When attempting to trade using the p2p dialogue, we are both able to select Pokemon to trade after waiting a very unreasonable amount of time. Usually it takes about 2 to 3 minutes for us to be able to select our Pokemon and sometimes we cannot select them at all as we will be stuck in a dialogue box. After three attempts, we were able to select our Pokemon, then after that the trade did not initiate even after waiting for up to five minutes. We were waiting with the dialogue box open, unable to do another. The game music still continued to play and NPCs moved around. We are using mGBA v. 0.10.1

### Steps To Reproduce

1) Connect to player for a trade
2) Attempt a trade

**Comment by televisionia** [comment]
Might do some testing to see what's causing this later... Might be slow connection issues though.

**Comment by TheHunterManX** [comment]
I cannot verify the issue, but please resubmit this issue if it persists after the 3.5 update.
