### ISSUE TITLE
[BUG]: A player is unable to join due to capacity limit.                               

### ISSUE THREAD

**Issue by ItsOwen1888** [TheHunterManX/GBA-PK-multiplayer#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Friends cant join due to server limit, How do I fix this?
How to increase server limit to 4

### Steps To Reproduce

.

**Comment by ItsOwen1888** [comment]
Is this alpha not meant for 4 players?

**Comment by televisionia** [comment]
Please make sure you have the right version, this might be because you aren't using version alpha 3. Otherwise, there might be a different bug going on. By the way, the 4 players also includes the player who is hosting the server. It isn't a dedicated server.

**Comment by TheHunterManX** [comment]
Player cap will be set to 8 default with 3.5 (soft cap, set it as high as you want), 4 is the max in 3.0
