### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by Unoaccaso** [TheHunterManX/GBA-PK-multiplayer#48]
I have great intrest in this project. I'm playing on a modded version of FR but I really miss the opportunity to battle that, I understood, will come in alpha 4. Is this active?

**Comment by televisionia** [comment]
You might have to directly communicate with the developer if you can find a way to. Though it is possible for someone/a group of people to make their own version if it and continue its development

**Comment by Unoaccaso** [comment]
So rn the project has stopped...

**Comment by televisionia** [comment]
Well, it's not stopped, who knows the maintainer might be working on a update right now without us knowing, but it's pretty silent at the moment.

**Comment by TheHunterManX** [comment]
Yes
