### ISSUE TITLE
[BUG]: Trade freezes game on "waiting for other player" dialog

### ISSUE THREAD

**Issue by v10k** [TheHunterManX/GBA-PK-multiplayer#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I'm playing with 3 friends on alpha 3, and we managed to exchange pokémon between us only once, if we try to trade again on the same session, one of the players will be stuck in the "waiting for other player" dialog, this can be reproduced by host and player / player and player interaction.

The way we find out to work around the problem is the host reloading the server script.

### Steps To Reproduce

1. Interact with other player on p2p dialogue and trade a pokemon once
2. After the trade is complete, attempt to trade again with the same player

**Comment by stevenstrick369** [comment]
Also seeing this bug but on every trade between me (server) and player 2 (client). we are using hamachi to connect.

**Comment by TheHunterManX** [comment]
Report again if this is in 3.5
