### ISSUE TITLE
Android Multiplayer

### ISSUE THREAD

**Issue by HarisOfNazareth** [TheHunterManX/GBA-PK-multiplayer#50]
Are you going to release an android emulator for 4 player pokemon battles?

**Comment by televisionia** [comment]
I think you'd have to wait for mgba to be ported to android, or at least the retroarch version having script support, the developer hasnt made much progress on this project for a while.

**Comment by TheHunterManX** [comment]
Yeah, mgba would need to be ported to android with script support.
