### ISSUE TITLE
No connection and low fps

### ISSUE THREAD

**Issue by TrueBloo** [TheHunterManX/GBA-PK-multiplayer#51]
Whenever either me or my friend try to load the client we drop to almost no fps and it never says that the client has connected to the server, were using Radmin VPN

**Comment by TrueBloo** [comment]
I just tried connecting a server and client on my PC and it worked fine so maybe because I'm trying  g to run it off of another program

**Comment by TrueBloo** [comment]
so i think my problem is im unable to create a local network with radmin or hamachi and I'm not sure how to fix that

**Comment by televisionia** [comment]
Could you provide more details on what steps you were taking? Were you both using a version 3 script? Did you make sure one person was using a server script and one person was using a client script and they both had the same IP address configuration?

**Comment by televisionia** [comment]
@TrueBloo Have you solved the problem yet?
