### ISSUE TITLE
hey, i'm having an important problem. pls reply asap

### ISSUE THREAD

**Issue by flame889** [TheHunterManX/GBA-PK-multiplayer#52]
i'm getting this message whenever i try to run the lua script, please reply asap.

"GBA-PK_Client.lua:29:** attempt to index global 'socket' (a nil value)"

I literally don't understand how to solve it
help

**Comment by televisionia** [comment]
Are you sure you're running this through the mgba script menu? You aren't meant to download lua and run it from there, you're meant to run it through the mgba script menu. If that still doesn't work try downloading the scripts again, maybe you accidentally edited something without knowing.

**Comment by Sure4Thing** [comment]
Can you walk through your steps to reproduce?
