### ISSUE TITLE
[BUG]: TIMEOUT

### ISSUE THREAD

**Issue by fatinpushan** [TheHunterManX/GBA-PK-multiplayer#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Hello, me and my friend are having trouble joining each other. We are using zeroTier both of use are connected to Zerotier. On my end (HOST) it saying he is connected but on his end it (CLIENT) it is not connected. Also, it keeps timing him out on my end and it says it is connected. someone, please help.  Also his game freeze  couple times when connecting. 

![1](https://github.com/TheHunterManX/GBA-PK-multiplayer/assets/56940042/91e5371c-0c59-4716-80ee-4dac12d1e1b2)

### Steps To Reproduce

1) Me and my friend both used ZeroTier 
2) I made a server and both of use connected to it 
3) We connected using "managed Adress" in ZeroTier 
4) He connected to me Port number was the same on video you have 
5) Name is less than 4 long 
6) I started the game then started the script 
7) Client started his game then started client script 
8) On my side it shows he is connected but every couple of seconds it times him out then reconnect 
9) on his side it does not show he is connected

**Comment by televisionia** [comment]
Try leaving the names blank, or just outright redownloading the scripts. Maybe there's something else going on here.
