### ISSUE TITLE
[BUG]: Client Doesn't connect and is laggy

### ISSUE THREAD

**Issue by RedUser01** [TheHunterManX/GBA-PK-multiplayer#57]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the bug

I did see a similar post about this but no fix for it so I thought I'd post a much more descriptive version. No matter who has the client script when they load it it states "Connected to server: no"  I've made sure that both the server and client have the same IP from the VPN and have the VPN on, I've made sure that both people are using Fire Red and I've made sure that we use the same emulator, so essentially  I made sure everything is correct but still no idea what the issue is. Any help would be amazing.

### Steps To Reproduce

1. Launch the Emulator
2. Load Fire Red
3. Launch the Client
4. The problem occurs

**Comment by televisionia** [comment]
#41 might be related to your issue.

I recommend leaving the nicknames blank.

**Comment by RedUser01** [comment]
Alright I'll let you know if that works thank you

**Comment by RedUser01** [comment]
Alright I'm still having the same issue this time I actually have images to show what's happening ( fixing the nicknames didn't work) First Image is Server and 2nd image is Client
![Capture](https://github.com/TheHunterManX/GBA-PK-multiplayer/assets/145228633/60f33a4a-b04e-491b-9c43-b14fcfc240be)
![Screenshot 2023-09-16 222132](https://github.com/TheHunterManX/GBA-PK-multiplayer/assets/145228633/48a2efa9-e858-4220-8780-83bbcacda6a1)

**Comment by televisionia** [comment]
Could you try just leaving the nicknames blank?

**Comment by RedUser01** [comment]
They were blank before I tried it and still only got that

**Comment by televisionia** [comment]
It's likely there's some kind of firewall or connection issue. I'm not sure. What 'VPN' are you using? If the server and the client are in the same network, are you making sure you're using your private IP within that network?

also sorry for the delay I didn't get the notification.

**Comment by RedUser01** [comment]
I used a vpn similar to the one that TheHunterMan used in his video, same setup just different name here's a link to the video of the guy I watched and the link to the VPN, his video isn't in English but he has English subtitles    
 https://www.youtube.com/watch?v=UexH_q1Tiyk&t=2s     https://www.vpn.net/

**Comment by televisionia** [comment]
I personally had trouble setting up with Hamachi, but I used ZeroTier and it worked just fine. By IP within the network I mean the IP given to you from Hamachi. Hosting servers like these may require a small amount of networking knowledge and how IP addresses work. Look for my tutorial at #35
