### ISSUE TITLE
when is alpha 4 coming out?[BUG]: 

### ISSUE THREAD

**Issue by Alonooooo** [TheHunterManX/GBA-PK-multiplayer#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I just want to know when alpha 4 is coming out because I desperately want to battle my friends and everyone says its coming out in alpha 4 soo

### Steps To Reproduce

can someone tell me?

**Comment by GuiTheDev** [comment]
Development seems to be halted, please close your issue or change tag to "question".

**Comment by televisionia** [comment]
> Development seems to be halted, please close your issue or change tag to "question".

@GuiTheDev Do you actually have this information from the TheHunterManX? Also, github issues are made for any kind of problem or question, they're just labelled for convenience. This isn't a discord server. It was probably misleading that it was labelled with bug though.

**Comment by GuiTheDev** [comment]
@televisionia hey, I said it "seems" not it "is", exactly because of that, I dont have information from the creator. And yeah, I said close or change label, if he wants he can reopen or create another one with the correct label, just trying to keep things organized.

**Comment by televisionia** [comment]
Alright
