### ISSUE TITLE
doesn't work properly

### ISSUE THREAD

**Issue by outsider66** [TheHunterManX/GBA-PK-multiplayer#6]
my friend and I were trying to play and suddently everytime he started the lua file it just said on my pc "user has succesfully connected" and then right after "user has timed out" on his pc it just said "you have been timed out" never even showed that he was connected to a server ("Connected to a server: no")
![imagem_2022-11-21_142625922](https://user-images.githubusercontent.com/118761398/203120956-6f54efc2-4f62-4c33-86da-5bdaeaf4fe0e.png)
![imagem_2022-11-21_142636430](https://user-images.githubusercontent.com/118761398/203120993-9818364f-0362-4b24-9457-6e2f0a290caa.png)
![image](https://user-images.githubusercontent.com/118761398/203121528-9f35d15d-2d35-41d6-ac44-de98decf5bc1.png)

 we also used hamachi

**Comment by Drakonas** [comment]
I have the same issue. I imagine the developer is aware of this as there are 4+ issues regarding this issue, all after the latest update which claims to have "fixed timeout issues". The developer is probably aware. I would just give them some time. This is alpha software, so it's going to be buggy. Give it some time.

**Comment by televisionia** [comment]
This is caused from the server's nickname being longer the 4 characters, I have a more in-depth explanation about the bug here: #41
