### ISSUE TITLE
Any New Updates Upcoming? Or This Project Is Closed?

### ISSUE THREAD

**Issue by Jagritisop** [TheHunterManX/GBA-PK-multiplayer#61]
Will the owner continue to update the mod? cuz i visited all i found about him and he seems inactive from all his accounts so is it safe to say this project is close? or will some random person will adapt to it and continue it? Anyone can tell me where is HunterMan gone and will we get more updates?

**Comment by HimoriK** [comment]
It's dead, there is progress being made on [this fork](https://github.com/loltag22/GBA-PK-multiplayer) though.
Looks like they will add to the multiplayer features.

**Comment by TheHunterManX** [comment]
I am alive and well, and 3.5 will be out this month.
