### ISSUE TITLE
[BUG]: it don’t w o r k

### ISSUE THREAD

**Issue by King-Mitrix** [TheHunterManX/GBA-PK-multiplayer#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I have the server file and it just says “gba-pk_server.lua:28: attempt to index a nil value (global ‘socket’) every time

### Steps To Reproduce

1. Download the file
2. Open the file through mgba’s script file thing
3. It doesn’t work 
![0106F5C3-3B95-4642-8A38-2212C35CE99C](https://github.com/TheHunterManX/GBA-PK-multiplayer/assets/95195320/de1cf574-9a42-4225-8104-8d6a5d574c69)

**Comment by TheHunterManX** [comment]
This is fixed in 3.5
