### ISSUE TITLE
[BUG]: Client File Chrashes PCs 

### ISSUE THREAD

**Issue by lorenzobose** [TheHunterManX/GBA-PK-multiplayer#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I've tried to run the Client File on both the computers,  but as soon as I load the script, the PCs slow down and the game crashes

### Steps To Reproduce

- Started The mGBA
- Loaded ROM
- Load Script Server
- Load Script Client
- Crash

**Comment by kriki200** [comment]
Did the client script connect?

**Comment by televisionia** [comment]
Means that the client script can't find the server, so its going on an infinite loop of waiting until it finds the IP address its looking for (there's no timeout I don't think) there are previous guides on other issues that probably might help you with your issue
