### ISSUE TITLE
[BUG]: fps drop from 60-12 every 2 seconds

### ISSUE THREAD

**Issue by Solohunter18** [TheHunterManX/GBA-PK-multiplayer#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

when the client ( me ) is playing on the server ( friend ), it runs smoothly for the server host but fps drop is happening for client, when i was host and my friend was client he got the fps drop, pls help because i rlly wanna play this with my friends without the frequent fps drop, i even tried this with me and my sister and same issue, client is getting fps drop, not just occasionally but every 2 seconds making it unplayable.

### Steps To Reproduce

open game
professor oak asking names questions, into and etc.
you experience the fps drop during all this and everything else after too so the entire game

**Comment by TheHunterManX** [comment]
Fixed in 3.5
