### ISSUE TITLE
[BUG]: Multiplayer battles not working in Fire Red, and Trading sometimes crashesh the game.

### ISSUE THREAD

**Issue by kriki200** [TheHunterManX/GBA-PK-multiplayer#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

If you try to battle with another player you get smth in the line of "Nothing happened..." when inviting him, we've tried with one pokemon, a few pokemon and a full party it didn't work in any of those scenarios. For the trading we managed to do one successful trade back and forth, but when trying a back and forth trade (evolving Haunter) the game crashed when we tried to send it back, it didn't even help tgo switch locations as once before the trade only crashed in a gym.

### Steps To Reproduce

Try to battle another player in game, for the second one try trading a pokemon back and forth.

**Comment by televisionia** [comment]
There's no battle support yet.
Well, there probably never will be, as the maintainer is no longer working on the project.

The trading crash seems interesting though

**Comment by TheHunterManX** [comment]
Trading crash is due to selecting slot 5 or 6, as 3.0 set variable 8004 to the slot you select, which just so happens to also be what decides the trade pokemon + trade trainer. Fixed in 3.5
