### ISSUE TITLE
[BUG]: Stuck Trying To get Friend Connected

### ISSUE THREAD

**Issue by pccolpman** [TheHunterManX/GBA-PK-multiplayer#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

My script is stuck here, I cannot get it to go past or connect. On his computer it says Connected: No. And we cant get this to change. We are trying to use Hamachi to play in different homes

Stuck at:

"Pokemon Leafgreen 1.1 detected. Script enabled.
Nickname is now sqel
Hosting game. Port forwarding may be required.
Searching for player...         "

Help please? I have edited the script with our Hamachi IPv4 and it wont connect still                                       

### Steps To Reproduce

Download the client and Server file. Change IP address to Hamachi IP address. Load ROM on client and server side. Run client and server script files. Attempt to connect failed.

**Comment by televisionia** [comment]
Read the other issues and their solutions.
