### ISSUE TITLE
[BUG]: After running script game does not connect my friend and I to each others server

### ISSUE THREAD

**Issue by Zkatula** [TheHunterManX/GBA-PK-multiplayer#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Hello, my friend and I heard about this mod and we got incredibly excited; unfortunately, every time we try to run the script it tells us that the client is not connected to the server. We are using radmin VPN and we changed the IP address in the client script, but no connection is occurring. I have tried looking at the other forums but I have had no success after looking for a few hours; I am really excited to play this mod so any help would be very appreciated. 

### Steps To Reproduce

Downloaded appropriate assets
Connected with my friend through Radmin VPN
Changed the client script in notepad to match my friend's IP address through Radmin VPN 
Ran the Rom
Ran the scripts
Frames drop considerably and at bottom of script pop-up it says "connected to server: no"

**Comment by TheHunterManX** [comment]
Fixed in 3.5
