### ISSUE TITLE
[BUG]: Repeated Arithmetic value nil | Connection happens but soon times out a few times before client begins repeated connecting to None

### ISSUE THREAD

**Issue by aencheng** [TheHunterManX/GBA-PK-multiplayer#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

![image](https://github.com/TheHunterManX/GBA-PK-multiplayer/assets/111991942/d6d80a9a-475b-4ed1-917e-bb33bdc49245)

Above is my server script run. I have followed the directions for ZeroTier that Tele has made in an earlier issue and made sure that is all correct. I've also checked to make sure the nickname is blank (""). 

After which I try to open the client script with the same ip (from ZeroTier) and nickname is blank on my friends pc and at first it starts connecting without an issue and as I navigate the beginning firered info before the gender and ign choosing, it starts to time my friend out and in a few times, which clearly shows that they're connecting properly. But then after a few times of that, it completely breaks. On my end, it repeatedly says some errors about nil values before completely timing my friend out and on my friends end, it breaks and just repeatedly prints "You have connected to None" and the "You have successfully connected" and "Connected to a server: Yes" changes repeatedly (within milliseconds) from searching the ip and port and No.

(Friend's Client Script Screen)
![image](https://github.com/TheHunterManX/GBA-PK-multiplayer/assets/111991942/5aac1225-7c4c-4d82-8b41-edfcf7402e85)

This is 30 Minutes later* - Now it's just freezing and refusing to connect

![image](https://github.com/TheHunterManX/GBA-PK-multiplayer/assets/111991942/825f78b1-0a12-443c-a6f3-654a79cff792)

### Steps To Reproduce

1. Ran through original download vid from creator
2. Ran and did instructions from Tele about ZeroTier
3. Ran it all together after changing IP and leaving Nickname blank

**Comment by LampadaLok** [comment]
I somehow managed to make it work not knowing anything about programming:

First part: 
When i opened the file (making it a .txt and reading it), i changed the IP address and followed all guides perfectly, and had the same problem.

Second part:
I looked for a solution online and found nothing, then i tried to open the file again and read it all

I found some random things that did not matter but most importantly i found something called
internet play
![image_2024-07-29_200307818](https://github.com/user-attachments/assets/18578e0b-d795-40cb-8f2a-8370ab49cf39)

and i tried to do some adjustments

![image_2024-07-29_200558923](https://github.com/user-attachments/assets/0e006c46-7d7e-4512-9ea4-587dc5972146)

i have no idea to why it did work this time, but it did, (pure luck)
and i still don't know which change solved the problem, you're free to explore

For clearance, 
i changed Local GameID from nothing to random shit,
changed Local EnableScript to true
and down in Internet Play, typed some random numbers inside socket.tcp brackets

I really didn't know what i was doing (as you can clearly see), but somehow it worked for me, if anyone who happens to know which part solved it, i'm happy to know.

**Comment by TheHunterManX** [comment]
Fixed in 3.5, which will be out this month
