### ISSUE TITLE
[BUG]: Battling does not work at all

### ISSUE THREAD

**Issue by Gekro123** [TheHunterManX/GBA-PK-multiplayer#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Player is busy or something like that will be shown when chosing for the battle option whilst interacting. Tried a bunch of stuff, nothing works, seen countless of messages like this from other players. Trading is the only thing that works at the moment.

Other then this, the script is good :) But please fix battling, it will make the code 100x more popular if it works

### Steps To Reproduce

See for yourself

**Comment by TheHunterManX** [comment]
I have stated many times that Alpha 4.0 will have battling, currently Alpha 3.5 does not support it.

**Comment by Gekro123** [comment]
Hey I am sorry, didn't knew you already stated that.

I know a Programmer who is willing to Help with the Battling Mode for Free, I can bring you guys in contact with eachother if you'd like.

**Comment by TheHunterManX** [comment]
Sure, you can send me a dm. My discord username is thehuntermanx.
