### ISSUE TITLE
[Feature request]: Please add gen2 game support

### ISSUE THREAD

**Issue by stephane-archer** [TheHunterManX/GBA-PK-multiplayer#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I would love to play Pokemon Crystal in multiplayer with my girlfriend

### Steps To Reproduce

you are the best, thank you for your project

**Comment by TheHunterManX** [comment]
If I do add it, it will come after alpha 4. I would also need to see how gbc games are structured.
