### ISSUE TITLE
[Question]: Does it support Pokémon Emerald Seaglass (room hack) or only official gen3 pokemon?

### ISSUE THREAD

**Issue by stephane-archer** [TheHunterManX/GBA-PK-multiplayer#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

it's not clear if this project supports ROM hacks or only official versions of gen3 Pokemon

### Steps To Reproduce

it's a question

**Comment by TheHunterManX** [comment]
The script does not officially support any hacks, however minor rom hacks will work with the script. Pokémon Emerald Seaglass does not work due to the extensive changes it makes.
