### ISSUE TITLE
Error connecting. Error type: unknown error

### ISSUE THREAD

**Issue by NumbProductions** [TheHunterManX/GBA-PK-multiplayer#74]
When trying to run the script i get prompt with an error code:

Started GBA-PK_Client.lua
Error connecting. Error type: unknown error
Please restart the script

Tried restarting multiple times, any fix?

**Comment by TheHunterManX** [comment]
This is caused when the connection does not go through. Please make sure you are using the correct IP and they are port forwarding

**Comment by NumbProductions** [comment]
How do i make sure we are using the correct IP and port forward?, We have tried many fixes cant seem to find one.

**Comment by TheHunterManX** [comment]
IP can be found on a public website like https://whatismyipaddress.com/ unless you are both using the same router, in which case you can find the ip address using ipconfig in command prompt. port forwarding tutorial can be found on youtube, which depending on the router can vary in how to do it. Port forwarding is only required on different routers.

**Comment by RoRo62-cr** [comment]
How do you do this with Hamachi? Will you need to port forward when using hamachi ? Also which Ip do I use the top one or the one the 2nd one?

https://github.com/user-attachments/assets/a0f282f7-2d86-4922-bc7d-eb7dde7cc7e3

**Comment by TheHunterManX** [comment]
You don't need port forwarding with hamachi, you can simply copy his IPv4 and paste it in client. Then when he runs the server.lua then you simply need to run the client.

**Comment by RoRo62-cr** [comment]
I am still having problems with the Error connecting. Error type: unknown error

I had to upload a link because it was more than 1 mb. https://www.youtube.com/watch?v=ZQRYozUzhCI 
Yes I know that we pasted the same ipv4 that was in there at 0:12 dw it is the ipv4 he copied in 0:02. Also yes I know I shared my ip.

Is there anything we did wrong for the error?

**Comment by RoRo62-cr** [comment]
?
