### ISSUE TITLE
Trading causes softlock

### ISSUE THREAD

**Issue by ultimate-vegan** [TheHunterManX/GBA-PK-multiplayer#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Sometimes when trading, either player (host or client) can be softlocked by the "waiting for other player" dialogue box after confirming a trade, forcing a reset as it cannot be cleared with any button. The trade screen where the pokemon is shown going between GBAs never appears. We are both using mGBA 0.11.7787-6aa558c4a and the alpha 2.6.1 version of the scripts on arch linux. 

### Steps To Reproduce

1. Initiate a trade
2. Confirm the trade

**Comment by SWHSmash** [comment]
can you reproduce this bug with current stable 0.10 version of mGBA?
'cause I for myself didn't got any problems currently

**Comment by ultimate-vegan** [comment]
> can you reproduce this bug with current stable 0.10 version of mGBA? 'cause I for myself didn't got any problems currently

we weren't able to use the scripts on 0.10, they wouldn't load into the script list when we tried

**Comment by BlazeITA** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Description of the bug
> Sometimes when trading, either player (host or client) can be softlocked by the "waiting for other player" dialogue box after confirming a trade, forcing a reset as it cannot be cleared with any button. The trade screen where the pokemon is shown going between GBAs never appears. We are both using mGBA 0.11.7787-6aa558c4a and the alpha 2.6.1 version of the scripts on arch linux.
> 
> ### Steps To Reproduce
> 1. Initiate a trade
> 2. Confirm the trade

To fix this problem I restared game and script.

**Comment by TheHunterManX** [comment]
A lot of the trading bugs be fixed in Alpha 3.5, which is coming within 2 weeks.
