### ISSUE TITLE
[Feature request]: 2 player double fight

### ISSUE THREAD

**Issue by stephane-archer** [TheHunterManX/GBA-PK-multiplayer#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Feature request: A two-player feature in which when one player enters a double fight, the other comes to help as a second player.

https://www.youtube.com/live/6o9ab73rDSE?si=pW9BovHRnQBbGIdJ&t=1936

### Steps To Reproduce

up

**Comment by TheHunterManX** [comment]
To request features, I suggest you put it in the discussions forum. This is not a bug, and therefore will be closed.

**Comment by stephane-archer** [comment]
What forum are you referring to?

**Comment by Deleca7755** [comment]
> What forum are you referring to?

probably https://github.com/TheHunterManX/GBA-PK-multiplayer/discussions @stephane-archer
