### ISSUE TITLE
[BUG]: Trading turns traded pokemon into invalid pokemon

### ISSUE THREAD

**Issue by ultimate-vegan** [TheHunterManX/GBA-PK-multiplayer#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Sometimes when trading, the traded pokemon you receive will show up as the question mark placeholder pokemon and will become an empty slot in the party screen. The empty slot prevents moving the selection past it. 
![Pokemon_-_FireRed_Version_USA_Europe_Rev_1-0](https://user-images.githubusercontent.com/37460972/204077113-8891347f-4141-4a44-8787-d574f5ad2789.png)

edit: after further attempts, we found that the pokemon can also sometimes turn into a bad egg instead of a blank space in the party

### Steps To Reproduce

1. Initiate a trade
2. Complete the trade

**Comment by SWHSmash** [comment]
can you reproduce this bug with current stable 0.10 version of mGBA?
'cause I for myself didn't got any problems currently

**Comment by m1n1m0th** [comment]
# Trade Data Transfer Issue

![pokemon_egg_bug](https://user-images.githubusercontent.com/113940953/204443882-5cc9e1e8-0902-41c7-ab63-2082692ea4c3.png)

## Description of Bug

While playing with my sister we encountered the trade bug. We are trying to use the other player in game as a way to fill the Pokédex faster. We noticed some consistencies and I have documented them below.

Attempted:

- Each player initiating trade, no affect, bug still occurs
- 4 Trades for each Pokémon, continuous problem

Encountered:

- (?) Pokémon
- Bad Egg Pokémon 

Pokémon consistently affected:

- Metapod
- Jigglypuff

**Comment by TheHunterManX** [comment]
A lot of the trading bugs be fixed in Alpha 3.5, which is coming within 2 weeks.
